/*******************************************************************************
 *
 * MIT License
 *
 * Copyright (c) 2023 erysdren (it/she)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 * 
 ******************************************************************************/

/*
 * define all the opcodes in one place
 */

QCVM_OPCODE(DONE)
QCVM_OPCODE(MUL_F)
QCVM_OPCODE(MUL_V)
QCVM_OPCODE(MUL_FV)
QCVM_OPCODE(MUL_VF)
QCVM_OPCODE(DIV_F)
QCVM_OPCODE(ADD_F)
QCVM_OPCODE(ADD_V)
QCVM_OPCODE(SUB_F)
QCVM_OPCODE(SUB_V)
QCVM_OPCODE(EQ_F)
QCVM_OPCODE(EQ_V)
QCVM_OPCODE(EQ_S)
QCVM_OPCODE(EQ_E)
QCVM_OPCODE(EQ_FNC)
QCVM_OPCODE(NE_F)
QCVM_OPCODE(NE_V)
QCVM_OPCODE(NE_S)
QCVM_OPCODE(NE_E)
QCVM_OPCODE(NE_FNC)
QCVM_OPCODE(LE)
QCVM_OPCODE(GE)
QCVM_OPCODE(LT)
QCVM_OPCODE(GT)
QCVM_OPCODE(LOAD_F)
QCVM_OPCODE(LOAD_V)
QCVM_OPCODE(LOAD_S)
QCVM_OPCODE(LOAD_ENT)
QCVM_OPCODE(LOAD_FLD)
QCVM_OPCODE(LOAD_FNC)
QCVM_OPCODE(ADDRESS)
QCVM_OPCODE(STORE_F)
QCVM_OPCODE(STORE_V)
QCVM_OPCODE(STORE_S)
QCVM_OPCODE(STORE_ENT)
QCVM_OPCODE(STORE_FLD)
QCVM_OPCODE(STORE_FNC)
QCVM_OPCODE(STOREP_F)
QCVM_OPCODE(STOREP_V)
QCVM_OPCODE(STOREP_S)
QCVM_OPCODE(STOREP_ENT)
QCVM_OPCODE(STOREP_FLD)
QCVM_OPCODE(STOREP_FNC)
QCVM_OPCODE(RETURN)
QCVM_OPCODE(NOT_F)
QCVM_OPCODE(NOT_V)
QCVM_OPCODE(NOT_S)
QCVM_OPCODE(NOT_ENT)
QCVM_OPCODE(NOT_FNC)
QCVM_OPCODE(IF)
QCVM_OPCODE(IFNOT)
QCVM_OPCODE(CALL0)
QCVM_OPCODE(CALL1)
QCVM_OPCODE(CALL2)
QCVM_OPCODE(CALL3)
QCVM_OPCODE(CALL4)
QCVM_OPCODE(CALL5)
QCVM_OPCODE(CALL6)
QCVM_OPCODE(CALL7)
QCVM_OPCODE(CALL8)
QCVM_OPCODE(STATE)
QCVM_OPCODE(GOTO)
QCVM_OPCODE(AND)
QCVM_OPCODE(OR)
QCVM_OPCODE(BITAND)
QCVM_OPCODE(BITOR)
QCVM_OPCODE(MULSTORE_F)
QCVM_OPCODE(MULSTORE_V)
QCVM_OPCODE(MULSTOREP_F)
QCVM_OPCODE(MULSTOREP_V)
QCVM_OPCODE(DIVSTORE_F)
QCVM_OPCODE(DIVSTOREP_F)
QCVM_OPCODE(ADDSTORE_F)
QCVM_OPCODE(ADDSTORE_V)
QCVM_OPCODE(ADDSTOREP_F)
QCVM_OPCODE(ADDSTOREP_V)
QCVM_OPCODE(SUBSTORE_F)
QCVM_OPCODE(SUBSTORE_V)
QCVM_OPCODE(SUBSTOREP_F)
QCVM_OPCODE(SUBSTOREP_V)
QCVM_OPCODE(FETCH_GBL_F)
QCVM_OPCODE(FETCH_GBL_V)
QCVM_OPCODE(FETCH_GBL_S)
QCVM_OPCODE(FETCH_GBL_E)
QCVM_OPCODE(FETCH_GBL_FNC)
QCVM_OPCODE(CSTATE)
QCVM_OPCODE(CWSTATE)
QCVM_OPCODE(THINKTIME)
QCVM_OPCODE(BITSET)
QCVM_OPCODE(BITSETP)
QCVM_OPCODE(BITCLR)
QCVM_OPCODE(BITCLRP)
QCVM_OPCODE(RAND0)
QCVM_OPCODE(RAND1)
QCVM_OPCODE(RAND2)
QCVM_OPCODE(RANDV0)
QCVM_OPCODE(RANDV1)
QCVM_OPCODE(RANDV2)
QCVM_OPCODE(SWITCH_F)
QCVM_OPCODE(SWITCH_V)
QCVM_OPCODE(SWITCH_S)
QCVM_OPCODE(SWITCH_E)
QCVM_OPCODE(SWITCH_FNC)
QCVM_OPCODE(CASE)
QCVM_OPCODE(CASERANGE)
